// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Appointment API",
    "version": "1"
  },
  "paths": {
    "/appointment": {
      "post": {
        "summary": "register",
        "description": "",
        "operationId": "register.post.appointment",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/appointment/{insuredId}": {
      "get": {
        "summary": "getByInsuredId",
        "description": "",
        "operationId": "getByInsuredId.get.appointment/{insuredId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "insuredId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};